In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle

In [2]:
data = pd.read_csv("student-mat.csv")
data.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [5]:
data = data[["G1", "G2", "G3", "studytime", "failures", "absences"]]
predict = "G3"
x = np.array(data.drop([predict], axis=1))
y = np.array(data[predict])


In [6]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)

In [7]:
linear_regression = LinearRegression()
linear_regression.fit(xtrain, ytrain)
accuracy = linear_regression.score(xtest, ytest)
print(accuracy)

0.7668348910387177


In [8]:
predictions = linear_regression.predict(xtest)
for i in range(len(predictions)):
    print(predictions[x], xtest[x], [ytest[x]])

[[ 8.61840393  8.47434364  5.93253606 13.91870048  8.47434364]
 [ 8.61840393  8.61840393  5.93253606 13.91870048  7.31180986]
 [13.07637321  6.5237457   5.93253606 14.239155    7.35431039]
 ...
 [ 7.35431039  6.5237457  11.30403362 14.239155   14.239155  ]
 [12.94401685 10.65085568 11.30403362 13.91870048 13.91870048]
 [ 6.5237457  13.81473796 11.30403362 13.91870048  8.61840393]] [[[ 9  9  2  0  6]
  [ 8  9  1  0  5]
  [ 7  7  2  1  2]
  [13 14  1  0  0]
  [ 8  9  1  0  5]]

 [[ 9  9  2  0  6]
  [ 9  9  2  0  6]
  [ 7  7  2  1  2]
  [13 14  1  0  0]
  [ 8  8  2  0  0]]

 [[14 13  3  1 12]
  [ 8  7  2  0  6]
  [ 7  7  2  1  2]
  [15 14  2  0  2]
  [ 8  9  1  3  0]]

 ...

 [[ 8  9  1  3  0]
  [ 8  7  2  0  6]
  [10 12  2  1  4]
  [15 14  2  0  2]
  [15 14  2  0  2]]

 [[13 13  1  0  0]
  [10 11  2  0  4]
  [10 12  2  1  4]
  [13 14  1  0  0]
  [13 14  1  0  0]]

 [[ 8  7  2  0  6]
  [11 14  1  0  6]
  [10 12  2  1  4]
  [13 14  1  0  0]
  [ 9  9  2  0  6]]] [array([[10,  9,  7, 14,  9]